[workspace]
authors = ["Essi Parent <9ivko1ozf@relay.firefox.com>"]
channels = ["conda-forge"]
name = "formation-2"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
marimo = ">=0.16.5"
pyarrow = ">=21.0.0"
polars = ">=1.34.0"
altair = ">=5.5.0"
ipykernel = ">=7.0.0"
jupyterlab = ">=4.4.9"
geopandas = ">=1.1.1"
rioxarray = ">=0.19.0"
geoviews = ">=1.14.1"
planetary-computer = ">=1.0.0"
altair_tiles = ">=0.4.0"
rasterstats = ">=0.20.0"
google-genai = ">=1.52.0"
openai = ">=2.8.1"
python = "3.13.*"

[pypi-dependencies]
lets-plot = ">=4.8.2, <5"
pydantic-ai = ">=1.5.0, <2"
